version: '2'
services:
    biauth-mysql:
        image: mysql:5.7.20
        # volumes:
        #     - ~/volumes/jhipster/biAuth/mysql/:/var/lib/mysql/
        environment:
            - MYSQL_USER=bi_auth
            - MYSQL_PASSWORD=bi_auth
            - MYSQL_DATABASE=bi_auth
        ports:
            - 3306:3306
        command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8mb4 --explicit_defaults_for_timestamp
